---
parse:
  title: "Category:Legacy Application"
  text:
    text: "<table style=\"\" class=\"metadata plainlinks ambox ambox-notice\">\n<tr>\n\
      <td class=\"ambox-image\">\n<div style=\"width:52px;\"><a href=\"/File:Oldwikilogo.png\"\
      \ class=\"image\" title=\"Legacy content notice\"><img alt=\"Legacy content\
      \ notice\" src=\"/w/images/thumb/Oldwikilogo.png/52px-Oldwikilogo.png\" width=\"\
      52\" height=\"37\" srcset=\"/w/images/Oldwikilogo.png 1.5x, /w/images/Oldwikilogo.png\
      \ 2x\" /></a></div>\n</td>\n<td class=\"ambox-text\">\n<p><b>This is a <a href=\"\
      /Category:Legacy_content\" title=\"Category:Legacy content\">legacy</a> category\
      \ <a href=\"/Unreal_Wiki:MediaWiki_conversion\" title=\"Unreal Wiki:MediaWiki\
      \ conversion\">imported</a> from the old Unreal Wiki.</b></p>\n<p><i>Please\
      \ avoid adding new articles to it.</i></p>\n</td>\n</tr>\n</table>\n<p>This\
      \ is the category of all pages about software packages.</p>\n<ul>\n<li>Members\
      \ of this category are listed below</li>\n<li>To add a page to this category:\
      \ Add the text <code>[[Category</code> <code>Application]]</code> to that page\
      \ so it will show on searches.</li>\n</ul>\n<p>All category pages belong to\
      \ <a href=\"/Category:Legacy_Category\" title=\"Category:Legacy Category\">Category:Legacy\
      \ Category</a>: Go there to find other categories.</p>\n<h2><span class=\"mw-headline\"\
      \ id=\"Related_Topics\">Related Topics</span><span class=\"mw-editsection\"\
      ><span class=\"mw-editsection-bracket\">[</span><a href=\"/edit/Category:Legacy_Application?section=1\"\
      \ title=\"Edit section: Related Topics\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<ul>\n<li><a href=\"/Legacy:Application\" title=\"Legacy:Application\"\
      >Application</a> – a hand-compiled list, subdivided into sections</li>\n<li><a\
      \ href=\"/Category:Legacy_Game\" title=\"Category:Legacy Game\">Category:Legacy\
      \ Game</a> – even though they're applications too, the actual games themselves\
      \ are sort of different in that they use content rather than create it.</li>\n\
      </ul>\n\n<!-- \nNewPP limit report\nCPU time usage: 0.060 seconds\nReal time\
      \ usage: 0.062 seconds\nPreprocessor visited node count: 50/1000000\nPreprocessor\
      \ generated node count: 259/1000000\nPost‐expand include size: 1054/2097152\
      \ bytes\nTemplate argument size: 296/2097152 bytes\nHighest expansion depth:\
      \ 5/40\nExpensive parser function count: 0/100\n-->\n\n<!-- \nTransclusion expansion\
      \ time report (%,ms,calls,template)\n100.00%    9.625      1 - -total\n100.00%\
      \    9.625      1 - Template:Legacy_category\n 53.96%    5.194      1 - Template:Ambox\n\
      -->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:813-0!*!0!*!*!5!*\
      \ and timestamp 20221117233350 and revision id 33653\n -->\n"
  categories:
  - sortkey: "Application"
    name: "Legacy_Category"
  - sortkey: "Application"
    name: "Legacy_content"
  - sortkey: "Applications"
    name: "Applications"
  links:
  - ns: 14
    exists: true
    name: "Category:Legacy content"
  - ns: 14
    exists: true
    name: "Category:Legacy Game"
  - ns: 14
    exists: true
    name: "Category:Legacy Category"
  - ns: 4
    exists: true
    name: "Unreal Wiki:MediaWiki conversion"
  - ns: 100
    exists: true
    name: "Legacy:Application"
  templates:
  - ns: 10
    exists: true
    name: "Template:Legacy category"
  - ns: 10
    exists: true
    name: "Template:Ambox"
  images:
  - "Oldwikilogo.png"
  externallinks: []
  sections:
  - toclevel: 1
    level: "2"
    line: "Related Topics"
    number: "1"
    index: "1"
    fromtitle: "Category:Legacy_Application"
    byteoffset: 362
    anchor: "Related_Topics"
  displaytitle: "Category:Legacy Application"
  iwlinks: []
  wikitext:
    text: "{{Legacy category}}\nThis is the category of all pages about software packages.\
      \ \n\n* Members of this category are listed below\n* To add a page to this category:\
      \ Add the text <code>[[Category</code><code> Application]]</code> to that page\
      \ so it will show on searches.\n\nAll category pages belong to [[:Category:Legacy\
      \ Category]]: Go there to find other categories.\n\n==Related Topics ==\n* [[Legacy:Application|Application]]\
      \ &ndash; a hand-compiled list, subdivided into sections\n* [[:Category:Legacy\
      \ Game]] &ndash; even though they're applications too, the actual games themselves\
      \ are sort of different in that they use content rather than create it.\n[[Category:Legacy\
      \ Category|Application]]\n[[Category:Applications|Applications]]"
  properties: []
  revId: 33653
name: "Category:Legacy Application"
revision:
  revid: 33653
  parentid: 2289
  user: "Wormbo"
  timestamp: 1229334373.000000000
  comment: "added to [[Category:Applications]]"
timestamp: 1668766323.237267000
