---
parse:
  title: "Default"
  text:
    text: "<table style=\"font-style: italic;\" class=\"metadata plainlinks ambox\
      \ ambox-info\">\n<tr>\n<td class=\"ambox-image\">\n<div style=\"width:52px;\"\
      ><a href=\"/File:Disambig.png\" class=\"image\"><img alt=\"Disambig.png\" src=\"\
      /w/images/Disambig.png\" width=\"30\" height=\"23\" /></a></div>\n</td>\n<td\
      \ class=\"ambox-text\">This disambiguation page lists articles associated with\
      \ the same title.<br />\nIf an <a href=\"/Special:WhatLinksHere/Default\" title=\"\
      Special:WhatLinksHere/Default\">internal link</a> led you here, you may wish\
      \ to change the link to point directly to the intended article.</td>\n</tr>\n\
      </table>\n<p>The UnrealScript keyword <b>Default</b> has two meanings. It can\
      \ be used to:</p>\n<ul>\n<li>access the default values of <a href=\"/Variables#Accessing_variables\"\
      \ title=\"Variables\">Variables</a>, or</li>\n<li>specify a default case for\
      \ the <a href=\"/Switch_statement\" title=\"Switch statement\">Switch statement</a>.</li>\n\
      </ul>\n\n<!-- \nNewPP limit report\nCPU time usage: 0.065 seconds\nReal time\
      \ usage: 0.134 seconds\nPreprocessor visited node count: 35/1000000\nPreprocessor\
      \ generated node count: 179/1000000\nPost‐expand include size: 982/2097152 bytes\n\
      Template argument size: 288/2097152 bytes\nHighest expansion depth: 4/40\nExpensive\
      \ parser function count: 0/100\n-->\n\n<!-- \nTransclusion expansion time report\
      \ (%,ms,calls,template)\n100.00%   16.200      1 - -total\n100.00%   16.200\
      \      1 - Template:Disambig\n 53.86%    8.726      1 - Template:Ambox\n-->\n\
      \n<!-- Saved in parser cache with key wiki:pcache:idhash:23791-0!*!0!*!*!5!*\
      \ and timestamp 20221117203911 and revision id 43270\n -->\n"
  categories:
  - sortkey: "Default"
    name: "Disambiguation"
  links:
  - ns: 0
    exists: true
    name: "Switch statement"
  - ns: 0
    exists: true
    name: "Variables"
  templates:
  - ns: 10
    exists: true
    name: "Template:Ambox"
  - ns: 10
    exists: true
    name: "Template:Disambig"
  images:
  - "Disambig.png"
  externallinks: []
  sections: []
  displaytitle: "Default"
  iwlinks: []
  wikitext:
    text: "{{disambig}}\nThe UnrealScript keyword '''Default''' has two meanings.\
      \ It can be used to:\n* access the default values of [[Variables#Accessing_variables|Variables]],\
      \ or\n* specify a default case for the [[Switch statement]]."
  properties: []
  revId: 43270
name: "Default"
revision:
  revid: 43270
  parentid: 33112
  user: "Eliot"
  timestamp: 1274089692.000000000
  comment: ""
timestamp: 1668760403.546045000
