---
parse:
  title: "Legacy:Modeling Application"
  text:
    text: "<p><b>Modeling Application</b> – an application used for creating 3D models.</p>\n\
      <h2><span class=\"mw-headline\" id=\"Model_Creation\">Model Creation</span><span\
      \ class=\"mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a\
      \ href=\"/edit/Legacy:Modeling_Application?section=1\" title=\"Edit section:\
      \ Model Creation\">edit</a><span class=\"mw-editsection-bracket\">]</span></span></h2>\n\
      <ul>\n<li><a href=\"/Legacy:3D_Studio_Max\" title=\"Legacy:3D Studio Max\">3D\
      \ Studio Max</a></li>\n<li><a href=\"/Legacy:Blender\" title=\"Legacy:Blender\"\
      \ class=\"mw-redirect\">Blender</a> (Free, Opensource)</li>\n<li><a href=\"\
      /Legacy:Gmax\" title=\"Legacy:Gmax\">gmax</a> (Free)</li>\n<li><a href=\"/Legacy:Lightwave\"\
      \ title=\"Legacy:Lightwave\">Lightwave</a></li>\n<li><a href=\"/Legacy:Maya\"\
      \ title=\"Legacy:Maya\">Maya</a> and Maya PLE (Personal Learning Edition) (Free)</li>\n\
      <li><a href=\"/Legacy:MilkShape\" title=\"Legacy:MilkShape\">MilkShape</a></li>\n\
      <li><a href=\"/Legacy:Rhinoceros\" title=\"Legacy:Rhinoceros\">Rhinoceros</a></li>\n\
      <li><a href=\"/Legacy:Softimage_XSI\" title=\"Legacy:Softimage XSI\">Softimage\
      \ XSI</a></li>\n<li><a href=\"/Legacy:Truespace\" title=\"Legacy:Truespace\"\
      >Truespace</a></li>\n<li><a href=\"/Legacy:Wings3D\" title=\"Legacy:Wings3D\"\
      >Wings3D</a> (Free, Opensource)</li>\n</ul>\n<h2><span class=\"mw-headline\"\
      \ id=\"Model_Conversion\">Model Conversion</span><span class=\"mw-editsection\"\
      ><span class=\"mw-editsection-bracket\">[</span><a href=\"/edit/Legacy:Modeling_Application?section=2\"\
      \ title=\"Edit section: Model Conversion\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<ul>\n<li><a href=\"/Legacy:3ds2unr\" title=\"Legacy:3ds2unr\"\
      >3ds2unr</a> – Utility that takes a .3DS file and converts to Unreal format\
      \ (*_d.3d and *_a.3d)\n<ul>\n<li><a rel=\"nofollow\" class=\"external text\"\
      \ href=\"http://unreal.epicgames.com/Models.htm\">Unreal Model Importing</a>\
      \ – 3ds2unr tutorial</li>\n</ul>\n</li>\n<li><a rel=\"nofollow\" class=\"external\
      \ text\" href=\"http://chimeric.beyondunreal.com/tools/u3d.zip\">Alternative\
      \ to 3ds2unr that adds a few extras</a></li>\n<li><a href=\"/Legacy:ActorX\"\
      \ title=\"Legacy:ActorX\">ActorX</a> – A plugin used to export skeletal animations\
      \ Available for <a href=\"/Legacy:Maya\" title=\"Legacy:Maya\">Maya</a> 3, 4/<a\
      \ href=\"/Legacy:3D_Studio_Max\" title=\"Legacy:3D Studio Max\">3D Studio Max</a>\
      \ 3.1, 4.0, 4.2 <a href=\"/Legacy:Softimage_XSI\" title=\"Legacy:Softimage XSI\"\
      >Softimage XSI</a> 4, 4.2, 5, 5.11</li>\n<li><a href=\"/Legacy:MeshMaker\" title=\"\
      Legacy:MeshMaker\">MeshMaker</a> – Converts UnrealEd <a href=\"/Legacy:Prefab\"\
      \ title=\"Legacy:Prefab\" class=\"mw-redirect\">prefabs</a> to <a href=\"/Legacy:Decoration\"\
      \ title=\"Legacy:Decoration\">decorations</a></li>\n<li><a rel=\"nofollow\"\
      \ class=\"external text\" href=\"http://www.unrealroc.com/Converter.html\">UnrealROC</a>\
      \ – Converts T3D to VRML/X3D/OBJ (textures,sounds,etc.)</li>\n<li><a href=\"\
      /Legacy:UTExporter\" title=\"Legacy:UTExporter\">UTExporter</a> – <a href=\"\
      /Legacy:3D_Studio_Max\" title=\"Legacy:3D Studio Max\">3D Studio Max</a> plugin\
      \ for exporting Unreal format models</li>\n<li><a rel=\"nofollow\" class=\"\
      external text\" href=\"http://home.mindspring.com/~iclint/carraraplug.html\"\
      >Carrara 2 Unreal</a> – export T3D, ASE, PSK and PSA from Eovia's Carrara 4</li>\n\
      </ul>\n<p>–Links that no longer work –</p>\n<ul>\n<li><a rel=\"nofollow\" class=\"\
      external autonumber\" href=\"http://www.project-blender.onlinehome.de/USM%201.1%20Script.zip\"\
      >[1]</a> – Blender plugin for exporting Unreal format models</li>\n</ul>\n<h2><span\
      \ class=\"mw-headline\" id=\"Related_Topics\">Related Topics</span><span class=\"\
      mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a href=\"/edit/Legacy:Modeling_Application?section=3\"\
      \ title=\"Edit section: Related Topics\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<ul>\n<li><a href=\"/Legacy:Topics_On_Modeling\" title=\"\
      Legacy:Topics On Modeling\">Topics On Modeling</a></li>\n<li><a href=\"/Legacy:Unreal_Modeling_FAQ\"\
      \ title=\"Legacy:Unreal Modeling FAQ\">Unreal Modeling FAQ</a></li>\n<li><a\
      \ href=\"/Legacy:Skinning\" title=\"Legacy:Skinning\">Skinning</a> – Applying\
      \ textures to your model</li>\n<li><a href=\"/Legacy:Animation\" title=\"Legacy:Animation\"\
      >Animation</a> – Making your model move</li>\n</ul>\n\n<!-- \nNewPP limit report\n\
      CPU time usage: 0.035 seconds\nReal time usage: 0.275 seconds\nPreprocessor\
      \ visited node count: 12/1000000\nPreprocessor generated node count: 24/1000000\n\
      Post‐expand include size: 20/2097152 bytes\nTemplate argument size: 0/2097152\
      \ bytes\nHighest expansion depth: 2/40\nExpensive parser function count: 0/100\n\
      -->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n100.00%\
      \    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:2104-0!*!0!!*!*!*\
      \ and timestamp 20221117200809 and revision id 5127\n -->\n"
  categories:
  - sortkey: "Modeling Application"
    name: "Legacy_Application"
  links:
  - ns: 100
    exists: true
    name: "Legacy:UTExporter"
  - ns: 100
    exists: true
    name: "Legacy:Maya"
  - ns: 100
    exists: true
    name: "Legacy:MeshMaker"
  - ns: 100
    exists: true
    name: "Legacy:Blender"
  - ns: 100
    exists: true
    name: "Legacy:3D Studio Max"
  - ns: 100
    exists: true
    name: "Legacy:Wings3D"
  - ns: 100
    exists: true
    name: "Legacy:Softimage XSI"
  - ns: 100
    exists: true
    name: "Legacy:ActorX"
  - ns: 100
    exists: true
    name: "Legacy:Gmax"
  - ns: 100
    exists: true
    name: "Legacy:Lightwave"
  - ns: 100
    exists: true
    name: "Legacy:MilkShape"
  - ns: 100
    exists: true
    name: "Legacy:Truespace"
  - ns: 100
    exists: true
    name: "Legacy:Skinning"
  - ns: 100
    exists: true
    name: "Legacy:Animation"
  - ns: 100
    exists: true
    name: "Legacy:Decoration"
  - ns: 100
    exists: true
    name: "Legacy:Rhinoceros"
  - ns: 100
    exists: true
    name: "Legacy:Prefab"
  - ns: 100
    exists: true
    name: "Legacy:3ds2unr"
  - ns: 100
    exists: true
    name: "Legacy:Unreal Modeling FAQ"
  - ns: 100
    exists: true
    name: "Legacy:Topics On Modeling"
  templates: []
  images: []
  externallinks:
  - "http://unreal.epicgames.com/Models.htm"
  - "http://www.project-blender.onlinehome.de/USM%201.1%20Script.zip"
  - "http://home.mindspring.com/~iclint/carraraplug.html"
  - "http://www.unrealroc.com/Converter.html"
  - "http://chimeric.beyondunreal.com/tools/u3d.zip"
  sections:
  - toclevel: 1
    level: "2"
    line: "Model Creation"
    number: "1"
    index: "1"
    fromtitle: "Legacy:Modeling_Application"
    byteoffset: 80
    anchor: "Model_Creation"
  - toclevel: 1
    level: "2"
    line: "Model Conversion"
    number: "2"
    index: "2"
    fromtitle: "Legacy:Modeling_Application"
    byteoffset: 513
    anchor: "Model_Conversion"
  - toclevel: 1
    level: "2"
    line: "Related Topics"
    number: "3"
    index: "3"
    fromtitle: "Legacy:Modeling_Application"
    byteoffset: 1730
    anchor: "Related_Topics"
  displaytitle: "Legacy:Modeling Application"
  iwlinks: []
  wikitext:
    text: "'''Modeling Application''' &ndash; an application used for creating 3D\
      \ models.\n\n==Model Creation==\n* [[Legacy:3D Studio Max|3D Studio Max]]\n\
      * [[Legacy:Blender|Blender]] (Free, Opensource)\n* [[Legacy:Gmax|gmax]] (Free)\n\
      * [[Legacy:Lightwave|Lightwave]]\n* [[Legacy:Maya|Maya]] and Maya PLE (Personal\
      \ Learning Edition) (Free)\n* [[Legacy:MilkShape|MilkShape]]\n* [[Legacy:Rhinoceros|Rhinoceros]]\n\
      * [[Legacy:Softimage XSI|Softimage XSI]]\n* [[Legacy:Truespace|Truespace]]\n\
      * [[Legacy:Wings3D|Wings3D]] (Free, Opensource)\n\n==Model Conversion==\n* [[Legacy:3ds2unr|3ds2unr]]\
      \ &ndash; Utility that takes a .3DS file and converts to Unreal format (*_d.3d\
      \ and *_a.3d)\n** [http://unreal.epicgames.com/Models.htm Unreal Model Importing]\
      \ &ndash; 3ds2unr tutorial\n* [http://chimeric.beyondunreal.com/tools/u3d.zip\
      \ Alternative to 3ds2unr that adds a few extras]\n* [[Legacy:ActorX|ActorX]]\
      \ &ndash; A plugin used to export skeletal animations Available for [[Legacy:Maya|Maya]]\
      \ 3, 4/[[Legacy:3D Studio Max|3D Studio Max]] 3.1, 4.0, 4.2 [[Legacy:Softimage\
      \ XSI|Softimage XSI]] 4, 4.2, 5, 5.11\n* [[Legacy:MeshMaker|MeshMaker]] &ndash;\
      \ Converts UnrealEd [[Legacy:Prefab|prefab]]s to [[Legacy:Decoration|decoration]]s\n\
      * [http://www.unrealroc.com/Converter.html UnrealROC] &ndash; Converts T3D to\
      \ VRML/X3D/OBJ (textures,sounds,etc.)\n* [[Legacy:UTExporter|UTExporter]] &ndash;\
      \ [[Legacy:3D Studio Max|3D Studio Max]] plugin for exporting Unreal format\
      \ models\n* [http://home.mindspring.com/~iclint/carraraplug.html Carrara 2 Unreal]\
      \ &ndash; export T3D, ASE, PSK and PSA from Eovia's Carrara 4\n\n&ndash;Links\
      \ that no longer work &ndash;\n* [http://www.project-blender.onlinehome.de/USM%201.1%20Script.zip]\
      \ &ndash; Blender plugin for exporting Unreal format models\n\n==Related Topics==\n\
      * [[Legacy:Topics On Modeling|Topics On Modeling]]\n* [[Legacy:Unreal Modeling\
      \ FAQ|Unreal Modeling FAQ]]\n* [[Legacy:Skinning|Skinning]] &ndash; Applying\
      \ textures to your model\n* [[Legacy:Animation|Animation]] &ndash; Making your\
      \ model move\n\n[[Category:Legacy Application|{{PAGENAME}}]]"
  properties: []
  revId: 5127
name: "Legacy:Modeling Application"
revision:
  revid: 5127
  parentid: 5129
  user: "Cpe-76-168-77-153.socal.res.rr.com"
  timestamp: 1179104764.000000000
  comment: "*"
timestamp: 1668763104.236263000
