---
parse:
  title: "Legacy:Mapping Application"
  text:
    text: "<p><a href=\"/Legacy:Application\" title=\"Legacy:Application\">Applications</a>\
      \ that are useful for mapping with <a href=\"/Legacy:UnrealEd\" title=\"Legacy:UnrealEd\"\
      \ class=\"mw-redirect\">UnrealEd</a>:</p>\n<p></p>\n<div id=\"toc\" class=\"\
      toc\">\n<div id=\"toctitle\">\n<h2>Contents</h2>\n</div>\n<ul>\n<li class=\"\
      toclevel-1 tocsection-1\"><a href=\"#General\"><span class=\"tocnumber\">1</span>\
      \ <span class=\"toctext\">General</span></a></li>\n<li class=\"toclevel-1 tocsection-2\"\
      ><a href=\"#Reference\"><span class=\"tocnumber\">2</span> <span class=\"toctext\"\
      >Reference</span></a></li>\n<li class=\"toclevel-1 tocsection-3\"><a href=\"\
      #Terrain_Creation\"><span class=\"tocnumber\">3</span> <span class=\"toctext\"\
      >Terrain Creation</span></a></li>\n<li class=\"toclevel-1 tocsection-4\"><a\
      \ href=\"#Botpathing_utilities\"><span class=\"tocnumber\">4</span> <span class=\"\
      toctext\">Botpathing utilities</span></a></li>\n<li class=\"toclevel-1 tocsection-5\"\
      ><a href=\"#Interface_Plugins\"><span class=\"tocnumber\">5</span> <span class=\"\
      toctext\">Interface Plugins</span></a></li>\n<li class=\"toclevel-1 tocsection-6\"\
      ><a href=\"#Related_Topics\"><span class=\"tocnumber\">6</span> <span class=\"\
      toctext\">Related Topics</span></a></li>\n<li class=\"toclevel-1 tocsection-7\"\
      ><a href=\"#Discussion\"><span class=\"tocnumber\">7</span> <span class=\"toctext\"\
      >Discussion</span></a></li>\n</ul>\n</div>\n<p></p>\n<h2><span class=\"mw-headline\"\
      \ id=\"General\">General</span><span class=\"mw-editsection\"><span class=\"\
      mw-editsection-bracket\">[</span><a href=\"/edit/Legacy:Mapping_Application?section=1\"\
      \ title=\"Edit section: General\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<ul>\n<li><a href=\"/Legacy:MapScale\" title=\"Legacy:MapScale\"\
      >MapScale</a> – scales the brushes and actors of a <a href=\"/Legacy:T3D_File\"\
      \ title=\"Legacy:T3D File\">T3D file</a></li>\n<li><a href=\"/Legacy:TexAlign\"\
      \ title=\"Legacy:TexAlign\">TexAlign</a> – superb tool for painless texture\
      \ alignment</li>\n<li><a href=\"/Legacy:UnrealFX\" title=\"Legacy:UnrealFX\"\
      >UnrealFX</a> – edits a mesh's poly flags individually</li>\n<li><a href=\"\
      /Legacy:UTToolkit\" title=\"Legacy:UTToolkit\">UTToolkit</a> – opens package\
      \ files and <a href=\"/Legacy:T3D_File\" title=\"Legacy:T3D File\">T3D files</a></li>\n\
      </ul>\n<h2><span class=\"mw-headline\" id=\"Reference\">Reference</span><span\
      \ class=\"mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a\
      \ href=\"/edit/Legacy:Mapping_Application?section=2\" title=\"Edit section:\
      \ Reference\">edit</a><span class=\"mw-editsection-bracket\">]</span></span></h2>\n\
      <ul>\n<li><a href=\"/Legacy:UTX-Viewer\" title=\"Legacy:UTX-Viewer\">UTX-Viewer</a>\
      \ – texture viewer</li>\n<li><a href=\"/Legacy:Mesh_Browser_Project\" title=\"\
      Legacy:Mesh Browser Project\">mesh browser project</a></li>\n</ul>\n<h2><span\
      \ class=\"mw-headline\" id=\"Terrain_Creation\">Terrain Creation</span><span\
      \ class=\"mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a\
      \ href=\"/edit/Legacy:Mapping_Application?section=3\" title=\"Edit section:\
      \ Terrain Creation\">edit</a><span class=\"mw-editsection-bracket\">]</span></span></h2>\n\
      <ul>\n<li><a href=\"/Legacy:TerraEdit\" title=\"Legacy:TerraEdit\">TerraEdit</a>\
      \ – Terrain editing program for UT generation. Makes importable brushes, v.\
      \ easy &amp; does (v. good) textures automatically.</li>\n<li><a href=\"/edit/Legacy:Terrain_Generator?redlink=1\"\
      \ class=\"new\" title=\"Legacy:Terrain Generator (page does not exist)\">Terrain\
      \ Generator</a> – latest version, 2.3.0 Beta adds support for export to an UnrealEd-compatible\
      \ format: <a rel=\"nofollow\" class=\"external free\" href=\"http://countermap.counter-strike.net/Nemesis/terrain.html\"\
      >http://countermap.counter-strike.net/Nemesis/terrain.html</a></li>\n<li>See\
      \ also <a href=\"/Legacy:Making_Terrain_(UT)\" title=\"Legacy:Making Terrain\
      \ (UT)\">Making Terrain (UT)</a></li>\n</ul>\n<h2><span class=\"mw-headline\"\
      \ id=\"Botpathing_utilities\">Botpathing utilities</span><span class=\"mw-editsection\"\
      ><span class=\"mw-editsection-bracket\">[</span><a href=\"/edit/Legacy:Mapping_Application?section=4\"\
      \ title=\"Edit section: Botpathing utilities\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<ul>\n<li><a href=\"/Legacy:Mind_Reader\" title=\"Legacy:Mind\
      \ Reader\">Mind Reader</a> (UT)</li>\n<li><a href=\"/Legacy:PathLogic\" title=\"\
      Legacy:PathLogic\">PathLogic</a> (UT) – place <a href=\"/Legacy:NavigationPoint\"\
      \ title=\"Legacy:NavigationPoint\">NavigationPoints</a> &amp; other <a href=\"\
      /Legacy:Bot_Support\" title=\"Legacy:Bot Support\">Bot Support</a> related actors\
      \ from within the game</li>\n</ul>\n<h2><span class=\"mw-headline\" id=\"Interface_Plugins\"\
      >Interface Plugins</span><span class=\"mw-editsection\"><span class=\"mw-editsection-bracket\"\
      >[</span><a href=\"/edit/Legacy:Mapping_Application?section=5\" title=\"Edit\
      \ section: Interface Plugins\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<p>Things that plug into <a href=\"/Legacy:UnrealEd\"\
      \ title=\"Legacy:UnrealEd\" class=\"mw-redirect\">UnrealEd</a></p>\n<ul>\n<li><a\
      \ href=\"/Legacy:Custom_Brushbuilder\" title=\"Legacy:Custom Brushbuilder\"\
      >Custom Brushbuilder</a> packages add buttons to the <a href=\"/Legacy:Brushbuilders\"\
      \ title=\"Legacy:Brushbuilders\">brushbuilders</a> in the <a href=\"/Legacy:Toolbox\"\
      \ title=\"Legacy:Toolbox\">toolbox</a></li>\n<li><a href=\"/Legacy:Custom_Toolbox_Buttons\"\
      \ title=\"Legacy:Custom Toolbox Buttons\">Custom Toolbox Buttons</a> add shortcuts\
      \ for <a href=\"/Legacy:UnrealEd_Console\" title=\"Legacy:UnrealEd Console\"\
      >UnrealEd console</a> commands into the last group of the <a href=\"/Legacy:Toolbox\"\
      \ title=\"Legacy:Toolbox\">Toolbox</a></li>\n<li><a href=\"/Legacy:Toolbar_Creator\"\
      \ title=\"Legacy:Toolbar Creator\" class=\"mw-redirect\">Toolbar Creator</a></li>\n\
      </ul>\n<h2><span class=\"mw-headline\" id=\"Related_Topics\">Related Topics</span><span\
      \ class=\"mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a\
      \ href=\"/edit/Legacy:Mapping_Application?section=6\" title=\"Edit section:\
      \ Related Topics\">edit</a><span class=\"mw-editsection-bracket\">]</span></span></h2>\n\
      <h2><span class=\"mw-headline\" id=\"Discussion\">Discussion</span><span class=\"\
      mw-editsection\"><span class=\"mw-editsection-bracket\">[</span><a href=\"/edit/Legacy:Mapping_Application?section=7\"\
      \ title=\"Edit section: Discussion\">edit</a><span class=\"mw-editsection-bracket\"\
      >]</span></span></h2>\n<p><b>SuperApe:</b> Added Category Application.</p>\n\
      \n<!-- \nNewPP limit report\nCPU time usage: 0.031 seconds\nReal time usage:\
      \ 0.086 seconds\nPreprocessor visited node count: 28/1000000\nPreprocessor generated\
      \ node count: 40/1000000\nPost‐expand include size: 19/2097152 bytes\nTemplate\
      \ argument size: 0/2097152 bytes\nHighest expansion depth: 2/40\nExpensive parser\
      \ function count: 0/100\n-->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n\
      100.00%    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key\
      \ wiki:pcache:idhash:2091-0!*!0!!en!*!* and timestamp 20221118023852 and revision\
      \ id 5093\n -->\n"
  categories:
  - sortkey: "Mapping Application"
    name: "Legacy_Application"
  links:
  - ns: 100
    exists: true
    name: "Legacy:NavigationPoint"
  - ns: 100
    exists: true
    name: "Legacy:Application"
  - ns: 100
    exists: true
    name: "Legacy:Making Terrain (UT)"
  - ns: 100
    exists: true
    name: "Legacy:Mesh Browser Project"
  - ns: 100
    exists: true
    name: "Legacy:T3D File"
  - ns: 100
    exists: true
    name: "Legacy:UnrealEd Console"
  - ns: 100
    exists: true
    name: "Legacy:Custom Toolbox Buttons"
  - ns: 100
    exists: true
    name: "Legacy:UTX-Viewer"
  - ns: 100
    exists: true
    name: "Legacy:Toolbar Creator"
  - ns: 100
    exists: true
    name: "Legacy:Toolbox"
  - ns: 100
    exists: true
    name: "Legacy:TerraEdit"
  - ns: 100
    exists: false
    name: "Legacy:Terrain Generator"
  - ns: 100
    exists: true
    name: "Legacy:UTToolkit"
  - ns: 100
    exists: true
    name: "Legacy:UnrealEd"
  - ns: 100
    exists: true
    name: "Legacy:Bot Support"
  - ns: 100
    exists: true
    name: "Legacy:Custom Brushbuilder"
  - ns: 100
    exists: true
    name: "Legacy:UnrealFX"
  - ns: 100
    exists: true
    name: "Legacy:TexAlign"
  - ns: 100
    exists: true
    name: "Legacy:Brushbuilders"
  - ns: 100
    exists: true
    name: "Legacy:MapScale"
  - ns: 100
    exists: true
    name: "Legacy:PathLogic"
  - ns: 100
    exists: true
    name: "Legacy:Mind Reader"
  templates: []
  images: []
  externallinks:
  - "http://countermap.counter-strike.net/Nemesis/terrain.html"
  sections:
  - toclevel: 1
    level: "2"
    line: "General"
    number: "1"
    index: "1"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 100
    anchor: "General"
  - toclevel: 1
    level: "2"
    line: "Reference"
    number: "2"
    index: "2"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 471
    anchor: "Reference"
  - toclevel: 1
    level: "2"
    line: "Terrain Creation"
    number: "3"
    index: "3"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 600
    anchor: "Terrain_Creation"
  - toclevel: 1
    level: "2"
    line: "Botpathing utilities"
    number: "4"
    index: "4"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 1044
    anchor: "Botpathing_utilities"
  - toclevel: 1
    level: "2"
    line: "Interface Plugins"
    number: "5"
    index: "5"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 1288
    anchor: "Interface_Plugins"
  - toclevel: 1
    level: "2"
    line: "Related Topics"
    number: "6"
    index: "6"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 1748
    anchor: "Related_Topics"
  - toclevel: 1
    level: "2"
    line: "Discussion"
    number: "7"
    index: "7"
    fromtitle: "Legacy:Mapping_Application"
    byteoffset: 1768
    anchor: "Discussion"
  displaytitle: "Legacy:Mapping Application"
  iwlinks: []
  wikitext:
    text: "[[Legacy:Application|Application]]s that are useful for mapping with [[Legacy:UnrealEd|UnrealEd]]:\n\
      \n==General==\n* [[Legacy:MapScale|MapScale]] &ndash; scales the brushes and\
      \ actors of a [[Legacy:T3D File|T3D file]]\n* [[Legacy:TexAlign|TexAlign]] &ndash;\
      \ superb tool for painless texture alignment\n* [[Legacy:UnrealFX|UnrealFX]]\
      \ &ndash; edits a mesh's poly flags individually\n* [[Legacy:UTToolkit|UTToolkit]]\
      \ &ndash; opens package files and [[Legacy:T3D File|T3D file]]s\n\n==Reference\
      \ ==\n* [[Legacy:UTX-Viewer|UTX-Viewer]] &ndash; texture viewer\n* [[Legacy:Mesh\
      \ Browser Project|mesh browser project]]\n\n==Terrain Creation ==\n* [[Legacy:TerraEdit|TerraEdit]]\
      \ &ndash; Terrain editing program for UT generation. Makes importable brushes,\
      \ v. easy & does (v. good) textures automatically.\n* [[Legacy:Terrain Generator|Terrain\
      \ Generator]] &ndash; latest version, 2.3.0 Beta adds support for export to\
      \ an UnrealEd-compatible format: http://countermap.counter-strike.net/Nemesis/terrain.html\n\
      * See also [[Legacy:Making Terrain (UT)|Making Terrain (UT)]]\n\n==Botpathing\
      \ utilities ==\n* [[Legacy:Mind Reader|Mind Reader]] (UT)\n* [[Legacy:PathLogic|PathLogic]]\
      \ (UT) &ndash; place [[Legacy:NavigationPoint|NavigationPoint]]s & other [[Legacy:Bot\
      \ Support|Bot Support]] related actors from within the game\n\n==Interface Plugins\
      \ ==\n\nThings that plug into [[Legacy:UnrealEd|UnrealEd]]\n* [[Legacy:Custom\
      \ Brushbuilder|Custom Brushbuilder]] packages add buttons to the [[Legacy:Brushbuilders|brushbuilders]]\
      \ in the [[Legacy:Toolbox|toolbox]]\n* [[Legacy:Custom Toolbox Buttons|Custom\
      \ Toolbox Buttons]] add shortcuts for [[Legacy:UnrealEd Console|UnrealEd console]]\
      \ commands into the last group of the [[Legacy:Toolbox|Toolbox]]\n* [[Legacy:Toolbar\
      \ Creator|Toolbar Creator]]\n\n==Related Topics==\n\n==Discussion==\n\n'''SuperApe:'''\
      \ Added Category Application.\n\n[[Category:Legacy Application|{{PAGENAME}}]]"
  properties: []
  revId: 5093
name: "Legacy:Mapping Application"
revision:
  revid: 5093
  parentid: 5095
  user: "SuperApe"
  timestamp: 1132194572.000000000
  comment: "*"
timestamp: 1668766301.896833000
