---
parse:
  title: "Local"
  text:
    text: "<div class=\"redirectMsg\"><p>Redirect to:</p><ul class=\"redirectText\"\
      ><li><a href=\"/Functions?redirect=no#Locals\" title=\"Functions\">Functions#Locals</a></li></ul></div>\n\
      <!-- \nNewPP limit report\nCPU time usage: 0.008 seconds\nReal time usage: 0.017\
      \ seconds\nPreprocessor visited node count: 0/1000000\nPreprocessor generated\
      \ node count: 2/1000000\nPost‐expand include size: 0/2097152 bytes\nTemplate\
      \ argument size: 0/2097152 bytes\nHighest expansion depth: 0/40\nExpensive parser\
      \ function count: 0/100\n-->\n\n<!-- \nTransclusion expansion time report (%,ms,calls,template)\n\
      100.00%    0.000      1 - -total\n-->\n\n<!-- Saved in parser cache with key\
      \ wiki:pcache:idhash:28976-0!*!*!*!*!*!* and timestamp 20221118083806 and revision\
      \ id 43363\n -->\n"
  categories: []
  links:
  - ns: 0
    exists: true
    name: "Functions"
  templates: []
  images: []
  externallinks: []
  sections: []
  displaytitle: "Local"
  iwlinks: []
  wikitext:
    text: "#Redirect [[Functions#Locals]]"
  properties: []
  revId: 43363
name: "Local"
revision:
  revid: 43363
  parentid: 0
  user: "Eliot"
  timestamp: 1274710395.000000000
  comment: "Redirected page to [[Functions#Locals]]"
timestamp: 1668760686.485650000
