---
parse:
  title: "Template:Navbox unrealapplications"
  text:
    text: "<p><b>Note:</b> This navbox may only reference official applications from\
      \ Epic Games that are related to the Unreal Engine.</p>\n<table class=\"navbox\
      \ nowraplinks\" style=\"\">\n<tr class=\"navbox-header\">\n<th colspan=\"2\"\
      \ class=\"navbox-header\" style=\"\">\n<div style=\"position:relative; width:100%;\
      \ white-space:nowrap;\">\n<div class=\"noprint plainlinks\" style=\"background-color:transparent;\
      \ padding:0; font-weight:normal; font-size:xx-small; white-space:nowrap; position:absolute;left:0.5em;\"\
      ><strong class=\"selflink\"><span title=\"View this template\">v</span></strong>&#160;•\
      &#160;<a href=\"/edit/Template_talk:Navbox_unrealapplications?redlink=1\" class=\"\
      new\" title=\"Template talk:Navbox unrealapplications (page does not exist)\"\
      ><span title=\"Discussion about this template\">d</span></a>&#160;•&#160;<a\
      \ rel=\"nofollow\" class=\"external text\" href=\"https://wiki.beyondunreal.com/edit/Template:Navbox_unrealapplications\"\
      ><span title=\"You can edit this template. Please use the preview button before\
      \ saving.\">e</span></a></div>\nUnreal applications</div>\n</th>\n</tr>\n<tr\
      \ class=\"navbox-body odd\">\n<th class=\"navbox-group\" style=\"\">Standalone</th>\n\
      <td class=\"navbox-body\" style=\"\"><a href=\"/Unreal_Engine_2_Runtime\" title=\"\
      Unreal Engine 2 Runtime\">Unreal Engine 2 Runtime</a>&#160;• <a href=\"/edit/Unreal_Development_Environment?redlink=1\"\
      \ class=\"new\" title=\"Unreal Development Environment (page does not exist)\"\
      >Unreal Development Environment</a>&#160;• <a href=\"/Unreal_Development_Kit\"\
      \ title=\"Unreal Development Kit\">Unreal Development Kit</a></td>\n</tr>\n\
      <tr class=\"navbox-body even\">\n<th class=\"navbox-group\" style=\"\">Bundled</th>\n\
      <td class=\"navbox-body\" style=\"\"><a href=\"/UnrealEd\" title=\"UnrealEd\"\
      \ class=\"mw-redirect\">UnrealEd</a>&#160;• <a href=\"/UnrealFrontend\" title=\"\
      UnrealFrontend\">UnrealFrontend</a>&#160;• <a href=\"/UnrealConsole\" title=\"\
      UnrealConsole\">UnrealConsole</a>&#160;• <a href=\"/edit/StatsViewer?redlink=1\"\
      \ class=\"new\" title=\"StatsViewer (page does not exist)\">StatsViewer</a>&#160;•\
      \ <a href=\"/edit/StatsThreshold?redlink=1\" class=\"new\" title=\"StatsThreshold\
      \ (page does not exist)\">StatsThreshold</a>&#160;• <a href=\"/edit/StatsComparison?redlink=1\"\
      \ class=\"new\" title=\"StatsComparison (page does not exist)\">StatsComparison</a>&#160;•\
      \ <a href=\"/edit/PackageDiffFrontEnd?redlink=1\" class=\"new\" title=\"PackageDiffFrontEnd\
      \ (page does not exist)\">PackageDiffFrontEnd</a>&#160;• <a href=\"/edit/CookerSync?redlink=1\"\
      \ class=\"new\" title=\"CookerSync (page does not exist)\">CookerSync</a>&#160;•\
      \ <a href=\"/edit/UnrealLoc?redlink=1\" class=\"new\" title=\"UnrealLoc (page\
      \ does not exist)\">UnrealLoc</a>&#160;• <a href=\"/edit/SwarmAgent?redlink=1\"\
      \ class=\"new\" title=\"SwarmAgent (page does not exist)\">SwarmAgent</a>&#160;•\
      \ <a href=\"/edit/SwarmCoordinator?redlink=1\" class=\"new\" title=\"SwarmCoordinator\
      \ (page does not exist)\">SwarmCoordinator</a>&#160;• <a href=\"/GameplayProfiler\"\
      \ title=\"GameplayProfiler\">GameplayProfiler</a>&#160;• <a href=\"/edit/UDebugger?redlink=1\"\
      \ class=\"new\" title=\"UDebugger (page does not exist)\">UDebugger</a>&#160;•\
      \ <a href=\"/edit/UPaint?redlink=1\" class=\"new\" title=\"UPaint (page does\
      \ not exist)\">UPaint</a>&#160;• <a href=\"/UCC\" title=\"UCC\">UCC</a>&#160;•\
      \ <a href=\"/edit/KarmaAuthoringTool?redlink=1\" class=\"new\" title=\"KarmaAuthoringTool\
      \ (page does not exist)\">KarmaAuthoringTool</a></td>\n</tr>\n</table>\n<div\
      \ class=\"template-documentation\">\n<div style=\"padding-bottom: 3px; border-bottom:\
      \ 1px solid #aaa; margin-bottom: 1ex\"><span class=\"editsection plainlinks\"\
      \ id=\"doc_editlinks\">[<a rel=\"nofollow\" class=\"external text\" href=\"\
      https://wiki.beyondunreal.com/edit/Template:Navbox_unrealapplications/doc?preload=Template:Documentation/preload\"\
      >create</a>]</span> <span style=\"font-size: 150%\">Documentation</span></div>\n\
      <div id=\"template_doc_page_transcluded\" class=\"dablink plainlinks\"></div>\n\
      </div>\n\n<!-- \nNewPP limit report\nCPU time usage: 0.061 seconds\nReal time\
      \ usage: 0.064 seconds\nPreprocessor visited node count: 126/1000000\nPreprocessor\
      \ generated node count: 1192/1000000\nPost‐expand include size: 4270/2097152\
      \ bytes\nTemplate argument size: 1212/2097152 bytes\nHighest expansion depth:\
      \ 6/40\nExpensive parser function count: 1/100\n-->\n\n<!-- \nTransclusion expansion\
      \ time report (%,ms,calls,template)\n100.00%   30.621      1 - -total\n 50.36%\
      \   15.421      1 - Template:Navbox\n 48.31%   14.794      1 - Template:Documentation\n\
      \ 12.13%    3.715      1 - Template:Tnavbar\n 12.05%    3.689      4 - Template:Documentation/docname\n\
      -->\n\n<!-- Saved in parser cache with key wiki:pcache:idhash:29019-0!*!0!*!*!*!*\
      \ and timestamp 20221118004114 and revision id 43528\n -->\n"
  categories: []
  links:
  - ns: 0
    exists: true
    name: "UCC"
  - ns: 0
    exists: false
    name: "StatsThreshold"
  - ns: 0
    exists: true
    name: "GameplayProfiler"
  - ns: 0
    exists: false
    name: "UDebugger"
  - ns: 10
    exists: false
    name: "Template:Navbox unrealapplications/doc"
  - ns: 0
    exists: false
    name: "StatsViewer"
  - ns: 0
    exists: false
    name: "PackageDiffFrontEnd"
  - ns: 0
    exists: false
    name: "KarmaAuthoringTool"
  - ns: 0
    exists: false
    name: "CookerSync"
  - ns: 0
    exists: true
    name: "Unreal Development Kit"
  - ns: 0
    exists: true
    name: "Unreal Engine 2 Runtime"
  - ns: 0
    exists: true
    name: "UnrealEd"
  - ns: 0
    exists: false
    name: "SwarmAgent"
  - ns: 0
    exists: true
    name: "UnrealConsole"
  - ns: 0
    exists: false
    name: "StatsComparison"
  - ns: 0
    exists: true
    name: "UnrealFrontend"
  - ns: 0
    exists: false
    name: "UnrealLoc"
  - ns: 0
    exists: false
    name: "Unreal Development Environment"
  - ns: 0
    exists: false
    name: "UPaint"
  - ns: 11
    exists: false
    name: "Template talk:Navbox unrealapplications"
  - ns: 0
    exists: false
    name: "SwarmCoordinator"
  templates:
  - ns: 10
    exists: true
    name: "Template:Documentation"
  - ns: 10
    exists: true
    name: "Template:Navbox"
  - ns: 10
    exists: true
    name: "Template:Tnavbar"
  - ns: 10
    exists: true
    name: "Template:Documentation/docname"
  images: []
  externallinks: []
  sections: []
  displaytitle: "Template:Navbox unrealapplications"
  iwlinks: []
  wikitext:
    text: "<noinclude>'''Note:''' This navbox may only reference official applications\
      \ from Epic Games that are related to the Unreal Engine.</noinclude>\n{{navbox\n\
      | name   = navbox unrealapplications\n| title  = Unreal applications\n\n\n|\
      \ group1 = Standalone\n| list1  = [[Unreal Engine 2 Runtime]]&nbsp;&bull; [[Unreal\
      \ Development Environment]]&nbsp;&bull; [[Unreal Development Kit]]\n\n| group2\
      \ = Bundled\n| list2  = [[UnrealEd]]&nbsp;&bull; [[UnrealFrontend]]&nbsp;&bull;\
      \ [[UnrealConsole]]&nbsp;&bull; [[StatsViewer]]&nbsp;&bull; [[StatsThreshold]]&nbsp;&bull;\
      \ [[StatsComparison]]&nbsp;&bull; [[PackageDiffFrontEnd]]&nbsp;&bull; [[CookerSync]]&nbsp;&bull;\
      \ [[UnrealLoc]]&nbsp;&bull; [[SwarmAgent]]&nbsp;&bull; [[SwarmCoordinator]]&nbsp;&bull;\
      \ [[GameplayProfiler]]&nbsp;&bull; [[UDebugger]]&nbsp;&bull; [[UPaint]]&nbsp;&bull;\
      \ [[UCC]]&nbsp;&bull; [[KarmaAuthoringTool]] \n}}<includeonly>\n{{#ifeq:{{#sub:{{PAGENAME}}|0|12}}|Official\
      \ Applications|[[Category:Official applications| {{PAGENAME}}]]|[[Category:Official\
      \ applications|{{PAGENAME}}]]}}\n</includeonly>\n<noinclude>{{documentation}}</noinclude>"
  properties:
  - name: "defaultsort"
    value: "Navbox unrealapplications"
  revId: 43528
name: "Template:Navbox unrealapplications"
revision:
  revid: 43528
  parentid: 43520
  user: "Eliot"
  timestamp: 1277351100.000000000
  comment: "Official Applications is probably a better name"
timestamp: 1668761113.171941000
